# Generated by Django 6.0.3 on 2026-03-07 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone_number', models.CharField(max_length=15)),
                ('specialty', models.CharField(choices=[('general', 'General'), ('cardiac', 'Cardiac'), ('trauma', 'Trauma'), ('neurology', 'Neurology'), ('pediatric', 'Pediatric')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icu_total', models.PositiveIntegerField(default=0)),
                ('icu_available', models.PositiveIntegerField(default=0)),
                ('bed_total', models.PositiveIntegerField(default=0)),
                ('bed_available', models.PositiveIntegerField(default=0)),
                ('has_ventilator', models.BooleanField(default=False)),
                ('has_blood_bank', models.BooleanField(default=False)),
                ('has_cath_lab', models.BooleanField(default=False)),
                ('is_accepting', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.hospital')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('accident', 'Road Accident'), ('heart_attack', 'Heart Attack'), ('stroke', 'Stroke'), ('burn', 'Burn Injury'), ('respiratory', 'Respiratory Failure'), ('other', 'Other Emergency')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('location_text', models.CharField(max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('needs_icu', models.BooleanField(default=False)),
                ('needs_ventilator', models.BooleanField(default=False)),
                ('needs_blood_bank', models.BooleanField(default=False)),
                ('needs_cath_lab', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('referred', 'Referred'), ('transferred', 'Transferred'), ('completed', 'Completed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('overridden', 'Overridden')], default='pending', max_length=15)),
                ('is_overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.hospital')),
                ('patient_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_request', to='core.patientevent')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.hospital')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.transferrequest')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('triage_submitted', 'Triage Submitted'), ('recommendation_viewed', 'Recommendation Viewed'), ('transfer_accepted', 'Transfer Accepted'), ('transfer_rejected', 'Transfer Rejected'), ('override_performed', 'Override Performed'), ('status_updated', 'Hospital Status Updated'), ('notification_sent', 'Notification Sent')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.patientevent')),
                ('transfer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.transferrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
