# Generated by Django 6.0.3 on 2026-04-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientevent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
