# Generated by Django 6.0.3 on 2026-04-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientevent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientevent',
            name='triage_level',
            field=models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('stable', 'Stable')], default='urgent', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientevent',
            name='case_type',
            field=models.CharField(choices=[('accident', 'Road Accident'), ('heart_attack', 'Heart Attack / Cardiac'), ('stroke', 'Stroke / Neurological'), ('burn', 'Burns'), ('fracture', 'Fracture / Trauma'), ('pediatric', 'Pediatric Emergency'), ('respiratory', 'Respiratory Distress'), ('other', 'Other')], max_length=20),
        ),
    ]
