# Generated by Django 6.0.3 on 2026-04-04 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_patientevent_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='core.hospital'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient / General User'), ('paramedic', 'Paramedic / Ambulance Operator'), ('hospital_admin', 'Hospital Administrator'), ('authority', 'Authority / Monitoring Officer'), ('admin', 'System Administrator')], default='paramedic', max_length=20),
        ),
    ]
