# Generated by Django 6.0.3 on 2026-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_hospital_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient / General User'), ('paramedic', 'Paramedic / Ambulance Operator'), ('hospital_admin', 'Hospital Administrator'), ('authority', 'Authority / Monitoring Officer'), ('admin', 'System Administrator')], default='patient', max_length=20),
        ),
    ]
